### ISSUE TITLE
Chrome Store Website Link Issue

### ISSUE THREAD

**Issue by elreydetoda** [gregolsky/chrome-app-search#1]
I guess you renamed the application in github, but forgot to change the name in the Google Chrome Webstore. I get a 404 when I click on it, which the link in the webstore is https://github.com/gregolsky/chrome-app-launcher not this repo. Again, I am sure you just changed the name but I wanted to let you know.
![2019-05-10-13:22:36_937x501](https://user-images.githubusercontent.com/10230166/57544933-d621c680-7326-11e9-81dd-c876abb2ae10.png)

**Comment by gregolsky** [comment]
Hi elreydetoda,
I am no longer the owner of Apps Launcher extension. Also this repository is for some old tryout extension I was working on and not the apps launcher.

**Comment by elreydetoda** [comment]
alright, sorry for the mix up and thank you!

**Comment by gtallen1187** [comment]
Hi @gregolsky - Do you happen to know who the current owner is for the Apps Launcher extension?  I'd love to check out the code and see if i can learn from it.

Also, for what it's worth, this `Chrome App Search` extension also sounds really useful, and i can't seem to find anything else like it on the webstore.  Are you open to some help taking this across the finish line?  I think this extension would be really useful, so I'm happy to do whatever I can to help out.

**Comment by gregolsky** [comment]
Apps Launcher extension's code is not available anymore.

`Chrome App Search` was never published, since it kind of duplicated part of the Apps Launcher at the time - if you used to trigger Apps Launcher with a keyboard shortcut search was there already.

It was feature complete when developed in 2013 IIRC. You can clone it and check it out, APIs might have changed and the tech stack here is quite ancient. Feel free to fork it and do whatever you want with the code :) Not sure if I'm able to provide much help there 6 years later, but feel free to ask.
